image: jangrewe/gitlab-ci-android

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
  - build
#   - test

lintDebug:
  stage: build
  only:
    refs:
    - master
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  only:
    refs:
    - master
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk


lintDebugManual:
  stage: build
  when: manual
  except:
    - master
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebugManual:
  stage: build
  when: manual
  except:
    - master
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk

# debugTests:
#   stage: test
#   script:
#     - ./gradlew -Pci --console=plain :app:testDebug